services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sv-users
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - backend-net

networks:
  backend-net:
    external: true
