INSERT INTO ROLES (ID, NAME) VALUES (1, 'ADMIN');
INSERT INTO ROLES (ID, NAME) VALUES (2, 'USER');

INSERT INTO USERS (ID, ROLE_ID, EMAIL, PASSWORD, USERNAME) VALUES (1, 1, 'admin@example.com', 'password', 'admin');
