CREATE TABLE IF NOT EXISTS ROLES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE_ID BIGINT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);
