
CREATE TABLE IF NOT EXISTS ROLES ( 
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS patients (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    IDENTIFICATION_TYPE VARCHAR(10) NOT NULL,
    IDENTIFICATION_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    LOCALIDAD VARCHAR(100) NOT NULL,
    BARRIO VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    nombre_familiar VARCHAR(255),
    PARENTESCO VARCHAR(100),
    foto VARCHAR(500) NULL
);

CREATE TABLE IF NOT EXISTS tratamiento (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    paciente_id BIGINT NOT NULL,
    medicamento VARCHAR(255) NOT NULL,
    dosis INT NOT NULL,
    frecuencia INT NOT NULL,
    dias_tratamiento INT NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    duracion INT NOT NULL,
    FOREIGN KEY (paciente_id) REFERENCES patients(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS procedimientos (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    paciente_id BIGINT NOT NULL,
    procedimiento VARCHAR(255) NOT NULL,
    frecuencia INT NOT NULL,
    dias_tratamiento INT NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    duracion INT NOT NULL,
    FOREIGN KEY (paciente_id) REFERENCES patients(id) ON DELETE CASCADE
);

